import os
from datetime import datetime
from tkinter import filedialog


class ReportExporter:
    def __init__(self):
        pass

    def export_txt(self, patient_info, symptoms, results, explanation, disease_info, save_path=None):
        if save_path is None:
            save_path = filedialog.asksaveasfilename(
                defaultextension=".txt",
                filetypes=[("Text files", "*.txt"), ("All files", "*.*")],
                initialfile=f"diagnosis_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt",
            )
        if not save_path:
            return None

        content = self._generate_report_text(patient_info, symptoms, results, explanation, disease_info)

        with open(save_path, "w", encoding="utf-8") as f:
            f.write(content)

        return save_path

    def _generate_report_text(self, patient_info, symptoms, results, explanation, disease_info):
        lines = []
        lines.append("=" * 60)
        lines.append("       MEDICAL DIAGNOSIS REPORT")
        lines.append("       AI-Based Medical Diagnosis Expert System")
        lines.append("=" * 60)
        lines.append("")

        lines.append(f"Report Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append("")

        lines.append("-" * 60)
        lines.append("PATIENT INFORMATION")
        lines.append("-" * 60)
        lines.append(f"Name: {patient_info.get('name', 'N/A')}")
        lines.append(f"Age: {patient_info.get('age', 'N/A')}")
        lines.append(f"Gender: {patient_info.get('gender', 'N/A')}")
        lines.append(f"Blood Type: {patient_info.get('blood_type', 'N/A')}")
        lines.append("")

        lines.append("-" * 60)
        lines.append("SELECTED SYMPTOMS")
        lines.append("-" * 60)
        for i, s in enumerate(symptoms, 1):
            lines.append(f"  {i}. {s.replace('_', ' ').title()}")
        lines.append("")

        lines.append("-" * 60)
        lines.append("DIAGNOSIS RESULTS")
        lines.append("-" * 60)
        lines.append(f"{'Rank':<6}{'Disease':<30}{'Confidence':<15}{'Matched/Total'}")
        lines.append("-" * 60)
        for i, r in enumerate(results, 1):
            disease_name = r["disease"].replace("_", " ").title()
            lines.append(f"{i:<6}{disease_name:<30}{r['confidence']}%{'':<12}{r['matched']}/{r['total']}")
        lines.append("")

        if results:
            top = results[0]
            lines.append("-" * 60)
            lines.append("TOP DIAGNOSIS DETAILS")
            lines.append("-" * 60)
            lines.append(f"Disease: {top['disease'].replace('_', ' ').title()}")
            lines.append(f"Category: {disease_info.get('category', 'N/A').title()}")
            lines.append(f"Confidence: {top['confidence']}%")
            lines.append("")
            lines.append("Description:")
            lines.append(f"  {disease_info.get('description', 'N/A')}")
            lines.append("")
            lines.append("Recommendation:")
            lines.append(f"  {disease_info.get('recommendation', 'N/A')}")
            lines.append("")

            if disease_info.get("is_emergency"):
                lines.append("*** EMERGENCY: This condition requires immediate medical attention ***")
                lines.append("")

        lines.append("-" * 60)
        lines.append("EXPLANATION")
        lines.append("-" * 60)
        lines.append(explanation)
        lines.append("")

        lines.append("=" * 60)
        lines.append("DISCLAIMER: This report is generated by an AI expert system for")
        lines.append("educational purposes only. It is NOT a substitute for professional")
        lines.append("medical diagnosis. Always consult a qualified healthcare provider.")
        lines.append("=" * 60)

        return "\n".join(lines)

    def export_history_txt(self, history, patient_info, save_path=None):
        if save_path is None:
            save_path = filedialog.asksaveasfilename(
                defaultextension=".txt",
                filetypes=[("Text files", "*.txt"), ("All files", "*.*")],
                initialfile=f"diagnosis_history_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt",
            )
        if not save_path:
            return None

        lines = []
        lines.append("=" * 60)
        lines.append("       DIAGNOSIS HISTORY REPORT")
        lines.append("=" * 60)
        lines.append("")
        lines.append(f"Patient: {patient_info.get('name', 'N/A')}")
        lines.append(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append(f"Total Records: {len(history)}")
        lines.append("")

        for i, entry in enumerate(history, 1):
            ts = entry.get("timestamp", "N/A")
            try:
                dt = datetime.fromisoformat(ts)
                ts = dt.strftime("%Y-%m-%d %H:%M:%S")
            except:
                pass

            lines.append(f"--- Record #{i} ---")
            lines.append(f"Date: {ts}")
            lines.append(f"Symptoms: {', '.join(s.replace('_', ' ').title() for s in entry.get('symptoms', []))}")
            lines.append(f"Top Diagnosis: {entry.get('top_disease', 'N/A').replace('_', ' ').title()}")
            lines.append(f"Confidence: {entry.get('confidence', 0)}%")
            lines.append("")

        with open(save_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))

        return save_path
